#!/bin/bash


# shellcheck disable=SC2034

REPOSITORY='airflow_in_podman'
PROJECT='airflow'
MAIN_PATH="/home/rchar01/Projects/${REPOSITORY}"
YAML_PATH="${MAIN_PATH}/_yaml"
BASH_PATH="${MAIN_PATH}/_bash"
YAML_DB=db
YAML_INIT=init
YAML_MAIN=main
ENV_FILE=.env
LOG_FILE=.log
ENV_PATH="${BASH_PATH}/${ENV_FILE}"
LOG_PATH="${BASH_PATH}/${LOG_FILE}"
NETWORK="airflow"
TIMEOUT_ATTEMPTS=20
TIMEOUT_SECONDS=10
AIRFLOW_DAGS_DIR=dags
AIRFLOW_LOGS_DIR=logs
AIRFLOW_PLUGINS_DIR=plugins
AIRFLOW_DAGS_PATH="${MAIN_PATH}/${PROJECT}_files/${AIRFLOW_DAGS_DIR}"
AIRFLOW_LOGS_PATH="${MAIN_PATH}/${PROJECT}_files/${AIRFLOW_LOGS_DIR}"
AIRFLOW_PLUGINS_PATH="${MAIN_PATH}/${PROJECT}_files/${AIRFLOW_PLUGINS_DIR}"
AIRFLOW_UID=$(id -u)
AIRFLOW_GID=0
INIT_CONTAINER_FLAG="start"
INIT_POD_FLAG="init"
AIRFLOW_IMAGE_DIR=image
AIRFLOW_IMAGE_PATH="${MAIN_PATH}/${AIRFLOW_IMAGE_DIR}"

#_AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
#_AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

JOB_COMPLETED_LOG="#container-job-completed#"
